esphome:
  name: esp-tcp-uart

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


external_components:
  - source: github://oxan/esphome-stream-server

uart:
  id: uart_bus
  rx_pin: GPIO5
  tx_pin: GPIO4
  baud_rate: 38400
  debug:
  
stream_server:
  uart_id: uart_bus
  port: 1234